services:
  - type: web
    name: backorder-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PICQER_SUBDOMAIN
        value: boottotaalnl
      - key: PICQER_API_KEY
        sync: false
      - key: PASS_LOUIS
        sync: false
      - key: PASS_LARS
        sync: false
      - key: PASS_BIRGIT
        sync: false
      - key: PASS_TIM
        sync: false
      - key: PASS_JORAN
        sync: false
